[2022-11-30T21:08:42.591+1300] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: load_kpi_view_dag.get_all_kpis scheduled__2022-11-30T07:00:00+00:00 [queued]>
[2022-11-30T21:08:42.611+1300] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: load_kpi_view_dag.get_all_kpis scheduled__2022-11-30T07:00:00+00:00 [queued]>
[2022-11-30T21:08:42.612+1300] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-30T21:08:42.612+1300] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-30T21:08:42.612+1300] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-30T21:08:42.629+1300] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): get_all_kpis> on 2022-11-30 07:00:00+00:00
[2022-11-30T21:08:42.642+1300] {standard_task_runner.py:55} INFO - Started process 89850 to run task
[2022-11-30T21:08:42.646+1300] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'load_kpi_view_dag', 'get_all_kpis', 'scheduled__2022-11-30T07:00:00+00:00', '--job-id', '156', '--raw', '--subdir', 'DAGS_FOLDER/load_kpi_view.py', '--cfg-path', '/var/folders/xc/5xlsywvn2n5d0_ty56lp12y80000gp/T/tmp_2z8t8q9']
[2022-11-30T21:08:42.648+1300] {standard_task_runner.py:83} INFO - Job 156: Subtask get_all_kpis
[2022-11-30T21:08:42.879+1300] {task_command.py:376} INFO - Running <TaskInstance: load_kpi_view_dag.get_all_kpis scheduled__2022-11-30T07:00:00+00:00 [running]> on host macbook-pro
[2022-11-30T21:08:43.022+1300] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=load_kpi_view_dag
AIRFLOW_CTX_TASK_ID=get_all_kpis
AIRFLOW_CTX_EXECUTION_DATE=2022-11-30T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-30T07:00:00+00:00
[2022-11-30T21:08:43.041+1300] {base.py:71} INFO - Using connection ID 'postgres_db' for task execution.
[2022-11-30T21:08:43.057+1300] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/hirenpatel/airflow/dags/load_kpi_view.py", line 45, in get_all_kpis
    cursor.execute(sql_stmt)
psycopg2.errors.UndefinedTable: relation "logs.kpi_view" does not exist
LINE 1: SELECT * FROM LOGS.KPI_VIEW
                      ^

[2022-11-30T21:08:43.084+1300] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=load_kpi_view_dag, task_id=get_all_kpis, execution_date=20221130T070000, start_date=20221130T080842, end_date=20221130T080843
[2022-11-30T21:08:43.095+1300] {standard_task_runner.py:100} ERROR - Failed to execute job 156 for task get_all_kpis (relation "logs.kpi_view" does not exist
LINE 1: SELECT * FROM LOGS.KPI_VIEW
                      ^
; 89850)
[2022-11-30T21:08:43.141+1300] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-11-30T21:08:43.225+1300] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
