[2022-12-04T00:03:21.793+1300] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: load_kpi_view_dag.get_all_kpis scheduled__2022-12-03T10:00:00+00:00 [queued]>
[2022-12-04T00:03:21.836+1300] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: load_kpi_view_dag.get_all_kpis scheduled__2022-12-03T10:00:00+00:00 [queued]>
[2022-12-04T00:03:21.837+1300] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-04T00:03:21.837+1300] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-12-04T00:03:21.837+1300] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-04T00:03:21.863+1300] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): get_all_kpis> on 2022-12-03 10:00:00+00:00
[2022-12-04T00:03:21.875+1300] {standard_task_runner.py:55} INFO - Started process 73325 to run task
[2022-12-04T00:03:21.880+1300] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'load_kpi_view_dag', 'get_all_kpis', 'scheduled__2022-12-03T10:00:00+00:00', '--job-id', '302', '--raw', '--subdir', 'DAGS_FOLDER/load_kpi_view.py', '--cfg-path', '/var/folders/xc/5xlsywvn2n5d0_ty56lp12y80000gp/T/tmp2olq3wi2']
[2022-12-04T00:03:21.882+1300] {standard_task_runner.py:83} INFO - Job 302: Subtask get_all_kpis
[2022-12-04T00:03:22.093+1300] {task_command.py:376} INFO - Running <TaskInstance: load_kpi_view_dag.get_all_kpis scheduled__2022-12-03T10:00:00+00:00 [running]> on host macbook-pro
[2022-12-04T00:03:22.230+1300] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=load_kpi_view_dag
AIRFLOW_CTX_TASK_ID=get_all_kpis
AIRFLOW_CTX_EXECUTION_DATE=2022-12-03T10:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-03T10:00:00+00:00
[2022-12-04T00:03:22.250+1300] {base.py:71} INFO - Using connection ID 'postgres_db' for task execution.
[2022-12-04T00:03:22.263+1300] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/hirenpatel/airflow/dags/load_kpi_view.py", line 38, in get_all_kpis
    cursor.execute(sql_stmt)
psycopg2.errors.UndefinedTable: relation "logs.kpi_view" does not exist
LINE 1: SELECT * FROM LOGS.KPI_VIEW
                      ^

[2022-12-04T00:03:22.283+1300] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=load_kpi_view_dag, task_id=get_all_kpis, execution_date=20221203T100000, start_date=20221203T110321, end_date=20221203T110322
[2022-12-04T00:03:22.299+1300] {standard_task_runner.py:100} ERROR - Failed to execute job 302 for task get_all_kpis (relation "logs.kpi_view" does not exist
LINE 1: SELECT * FROM LOGS.KPI_VIEW
                      ^
; 73325)
[2022-12-04T00:03:22.343+1300] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-12-04T00:03:22.424+1300] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
