[2022-12-01T10:11:18.707+1300] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: load_kpi_view_dag.get_all_kpis manual__2022-11-30T21:11:15.103389+00:00 [queued]>
[2022-12-01T10:11:18.719+1300] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: load_kpi_view_dag.get_all_kpis manual__2022-11-30T21:11:15.103389+00:00 [queued]>
[2022-12-01T10:11:18.719+1300] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-01T10:11:18.720+1300] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-12-01T10:11:18.720+1300] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-01T10:11:18.729+1300] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): get_all_kpis> on 2022-11-30 21:11:15.103389+00:00
[2022-12-01T10:11:18.735+1300] {standard_task_runner.py:55} INFO - Started process 85619 to run task
[2022-12-01T10:11:18.739+1300] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'load_kpi_view_dag', 'get_all_kpis', 'manual__2022-11-30T21:11:15.103389+00:00', '--job-id', '196', '--raw', '--subdir', 'DAGS_FOLDER/load_kpi_view.py', '--cfg-path', '/var/folders/xc/5xlsywvn2n5d0_ty56lp12y80000gp/T/tmpu1kksoal']
[2022-12-01T10:11:18.741+1300] {standard_task_runner.py:83} INFO - Job 196: Subtask get_all_kpis
[2022-12-01T10:11:18.903+1300] {task_command.py:376} INFO - Running <TaskInstance: load_kpi_view_dag.get_all_kpis manual__2022-11-30T21:11:15.103389+00:00 [running]> on host macbook-pro.hq.optimalbi.site
[2022-12-01T10:11:18.956+1300] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=load_kpi_view_dag
AIRFLOW_CTX_TASK_ID=get_all_kpis
AIRFLOW_CTX_EXECUTION_DATE=2022-11-30T21:11:15.103389+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-30T21:11:15.103389+00:00
[2022-12-01T10:11:18.967+1300] {base.py:71} INFO - Using connection ID 'postgres_db' for task execution.
[2022-12-01T10:11:18.974+1300] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/hirenpatel/airflow/dags/load_kpi_view.py", line 38, in get_all_kpis
    cursor.execute(sql_stmt)
psycopg2.errors.UndefinedTable: relation "logs.kpi_view" does not exist
LINE 1: SELECT * FROM LOGS.KPI_VIEW
                      ^

[2022-12-01T10:11:18.988+1300] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=load_kpi_view_dag, task_id=get_all_kpis, execution_date=20221130T211115, start_date=20221130T211118, end_date=20221130T211118
[2022-12-01T10:11:18.994+1300] {standard_task_runner.py:100} ERROR - Failed to execute job 196 for task get_all_kpis (relation "logs.kpi_view" does not exist
LINE 1: SELECT * FROM LOGS.KPI_VIEW
                      ^
; 85619)
[2022-12-01T10:11:19.017+1300] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-12-01T10:11:19.089+1300] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
